import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
        <head />
        <body className="bg-gray-100 text-gray-900">
        <header className="bg-blue-600 text-white p-4 text-center">
            <h1 className="text-2xl">📋 게시판</h1>
        </header>
        <main>{children}</main>
        <footer className="bg-gray-200 text-center p-4">
            <p>© 2025 My Website</p>
        </footer>
        </body>
        </html>
    );
}
